"""empty message

Revision ID: ab3849379edf
Revises: b84d7ced93a5
Create Date: 2024-11-25 14:08:15.926028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3849379edf'
down_revision = 'b84d7ced93a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_two_factor_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('secret_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('secret_token')
        batch_op.drop_column('is_two_factor_enabled')

    # ### end Alembic commands ###
